import type { Metadata } from "next";
import "./globals.css";
import AuthUserProvider from "./Context/AuthUserProvider";
import AppHeader from "./components/layouts/AppHeader";
import AppFooter from "./components/layouts/AppFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className='flex flex-col items-center min-h-screen relative overflow-x-hidden'>
      <AuthUserProvider>
        <AppHeader />
          {children}
        <AppFooter />
      </AuthUserProvider>
      </body>
    </html>
  );
}
