import type { Metadata } from "next";
import "./globals.css";
import { Albert_Sans } from "next/font/google";
import AuthUserProvider from "./Context/AuthUserProvider";
import AppHeader from "./components/layouts/AppHeader";
import AppFooter from "./components/layouts/AppFooter";

const albertSans = Albert_Sans({
  subsets: ["latin"],
  variable: "--font-albert-sans",
  // weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`min-h-screen relative overflow-x-hidden ${albertSans.className}`}>
      <AuthUserProvider>
        {/* <AppHeader /> */}
          {children}
        {/* <AppFooter /> */}
      </AuthUserProvider>
      </body>
    </html>
  );
}
