import type { Metadata } from "next";
import "./globals.css";
import { Albert_Sans } from "next/font/google";
import AuthUserProvider from "./Context/AuthContext/AuthUserProvider";
import AppHeader from "./components/layouts/AppHeader";
import AppFooter from "./components/layouts/AppFooter";
import DarkOverlayProvider from "./Context/DarkOverlayContext/DarkOverlayProvider";

const albertSans = Albert_Sans({
  subsets: ["latin"],
  variable: "--font-albert-sans",
  // weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={`min-h-screen relative overflow-x-hidden ${albertSans.className}`}>
        {/* <div className={`dark-overlay absolute top-0 left-0 w-full h-full bg-black/25 z-40 `}></div> */}
        <AuthUserProvider>
          {children}
        </AuthUserProvider>
      </body>
    </html>
  );
}
