services:

  reverse-proxy:
      image: traefik:v3.0
      command:
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
        - "--certificatesresolvers.myresolver.acme.email=marc.assi@sajed-engineering.com"
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro

  frontend_landing:
    container_name: frontend-landing
    build: 
      context: ./frontend/marketing
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3000"
    env_file:
      - ./frontend/marketing/.env
    depends_on:
      - backend
    networks:
      - klippio-network

  frontend:
    container_name: frontend-app
    build: 
      context: ./frontend/application
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/application/.env
    depends_on:
      - backend
    networks:
      - klippio-network

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    # ports:
    #   - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - klippio-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.klippio.fr`)" # 💡 Ton sous-domaine API
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432"
    networks:
      - klippio-network

volumes:
  db_data:

networks:
  klippio-network:
    driver: bridge