services:

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - klippio-network
    
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - klippio-network

  # Ajouter mailpit
  mailer:
    container_name: mailer
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - klippio-network

volumes:
  db_data:

networks:
  klippio-network:
    driver: bridge