services:

  reverse-proxy:
      image: traefik:v3.0
      restart: unless-stopped
      container_name: traefik
      command:
        - "--providers.docker=true"
        - "--providers.docker.exposedbydefault=false"
        - "--providers.docker.endpoint=unix:///var/run/docker.sock"
        - "--entrypoints.web.address=:80"
        - "--entrypoints.websecure.address=:443"
        - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
        - "--certificatesresolvers.myresolver.acme.email=marc.assi@sajed-engineering.com"
      environment:
      # Force Traefik à utiliser une version d'API supportée par Debian moderne
      - DOCKER_API_VERSION=1.40
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
      networks:
        - klippio-network

  frontend_landing:
    restart: unless-stopped
    container_name: frontend-landing
    build: 
      context: ./frontend/marketing
      dockerfile: Dockerfile.prod
    env_file:
      - ./frontend/marketing/.env
    networks:
      - klippio-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-landing.rule=Host(`klippio.sajed-engineering.com`)" # 💡 Ton sous-domaine Application
      - "traefik.http.routers.frontend-landing.entrypoints=websecure"
      - "traefik.http.routers.frontend-landing.tls.certresolver=myresolver"
      - "traefik.http.services.frontend-landing.loadbalancer.server.port=3001"

  frontend:
    restart: unless-stopped
    container_name: frontend-app
    build: 
      context: ./frontend/application
      dockerfile: Dockerfile.prod
    env_file:
      - ./frontend/application/.env
    depends_on:
      - backend
    networks:
      - klippio-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-app.rule=Host(`app.klippio.sajed-engineering.com`)" # 💡 Ton sous-domaine Application
      - "traefik.http.routers.frontend-app.entrypoints=websecure"
      - "traefik.http.routers.frontend-app.tls.certresolver=myresolver"
      - "traefik.http.services.frontend-app.loadbalancer.server.port=3000"

  backend:
    restart: unless-stopped
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file:
      - ./backend/.env
    networks:
      - klippio-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.klippio.sajed-engineering.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  db:
    restart: unless-stopped
    container_name: db
    image: postgres:18
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - klippio-network

volumes:
  db_data:

networks:
  klippio-network:
    driver: bridge