FROM node:24-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx prisma generate
RUN npm run build

FROM node:24-alpine AS runner
WORKDIR /app
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
RUN npm ci --only=production
COPY --from=builder /app/dist ./dist
COPY ./entrypoint.sh ./


RUN chown -R node:node /app
USER node
EXPOSE 8000
ENTRYPOINT ["./entrypoint.sh"]
CMD ["npm", "run", "start:prod"]