FROM node:24-alpine

ARG NEXT_PUBLIC_APP_URL

ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL

WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN chown -R node:node /app
USER node
ENV NODE_ENV=production

RUN npm run build
EXPOSE 3001

CMD ["npm", "run", "start"]