FROM node:24-alpine AS builder

ARG NEXT_PUBLIC_BACKEND_URL
ARG NEXT_PUBLIC_AMAZON_S3_REGION
ARG NEXT_PUBLIC_AMAZON_S3_BUCKET_NAME

ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
ENV NEXT_PUBLIC_AMAZON_S3_REGION=$NEXT_PUBLIC_AMAZON_S3_REGION
ENV NEXT_PUBLIC_AMAZON_S3_BUCKET_NAME=$NEXT_PUBLIC_AMAZON_S3_BUCKET_NAME

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build 

FROM node:24-alpine AS runner
ENV NODE_ENV=production
WORKDIR /app
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
EXPOSE 3000
CMD ["npm", "start"]